_target_: the_well.benchmark.models.FNOFiLM
modes1: 16
modes2: 16
hidden_channels: 128
#num_blocks: [1, 1, 1, 1]
##############
# FiLM configs
##############
film_naive: False                # naive FiLM: augment model inputs with time and/or cooling information
film_naive_use_embedding: False      # use sinusoidal embeddings for time/cooling inputs in naive FiLM
film_time: False                  # either film_time or film_t_cool has to be True, or both
film_t_cool: True
