_target_: the_well.benchmark.trainer.Trainer
epochs: 100
val_frequency: 1
rollout_val_frequency: 2
short_validation_length: 20
max_rollout_steps: 100
num_time_intervals: 5
make_rollout_videos: False
checkpoint_frequency: 0 # Frequency of saving checkpoints. If 0, only use best/most recent. Setting this to 1 uses A LOT of disk space.
# enable_amp: True
loss_fn: ???
checkpoint_path: "" # This is a default that is overridden by the code
###############
# added configs
###############
# pushforward configs
pushforward: False
pushforward_final_probs: [0.4, 0.2, 0.2, 0.2]
pushforward_warmup_epochs: 30
film: True # other FiLM params are in the model config
